[2024-12-05T06:11:02.890+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T06:11:02.911+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-05T06:10:00+00:00 [queued]>
[2024-12-05T06:11:02.924+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-05T06:10:00+00:00 [queued]>
[2024-12-05T06:11:02.924+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-05T06:11:02.949+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-05 06:10:00+00:00
[2024-12-05T06:11:02.956+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T06:11:02.958+0000] {standard_task_runner.py:72} INFO - Started process 131 to run task
[2024-12-05T06:11:02.959+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-05T06:10:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmp6hylfhs9']
[2024-12-05T06:11:02.960+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask generate_and_store_data
[2024-12-05T06:11:03.023+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-05T06:10:00+00:00 [running]> on host bae2c2d03db8
[2024-12-05T06:11:03.133+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T06:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-05T06:10:00+00:00'
[2024-12-05T06:11:03.135+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-05T06:11:03.135+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-05T06:11:03.135+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-05 06:11:02.912378+00:00
[2024-12-05T06:11:03.136+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-05T06:11:03.136+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T06:11:03.137+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/finance_data_generator.py", line 21, in generate_and_store_data
    df = generate_financial_transactions()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/data_generator.py", line 70, in generate_financial_transactions
    'transaction_id': generate_transaction_ids(size),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/data_generator.py", line 27, in generate_transaction_ids
    ids = range(start_id + 1, start_id + size + 1)
                ~~~~~~~~~^~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/finance_data_generator.py", line 25, in generate_and_store_data
    raise AirflowFailException(f"Data generation or storage failed: {e}")
airflow.exceptions.AirflowFailException: Data generation or storage failed: unsupported operand type(s) for +: 'NoneType' and 'int'
[2024-12-05T06:11:03.148+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-05T06:11:03.149+0000] {logging_mixin.py:190} INFO - Task start:2024-12-05 06:11:02.912378+00:00 end:2024-12-05 06:11:03.148307+00:00 duration:0.235929
[2024-12-05T06:11:03.150+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): generate_and_store_data> dag:<DAG: finance_data_generator> dagrun:<DagRun finance_data_generator @ 2024-12-05 06:10:00+00:00: scheduled__2024-12-05T06:10:00+00:00, state:running, queued_at: 2024-12-05 06:11:00.805924+00:00. externally triggered: False>
[2024-12-05T06:11:03.150+0000] {logging_mixin.py:190} INFO - Failure caused by Data generation or storage failed: unsupported operand type(s) for +: 'NoneType' and 'int'
[2024-12-05T06:11:03.150+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-05T06:10:00+00:00, execution_date=20241205T061000, start_date=20241205T061102, end_date=20241205T061103
[2024-12-05T06:11:03.166+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T06:11:03.167+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task generate_and_store_data (Data generation or storage failed: unsupported operand type(s) for +: 'NoneType' and 'int'; 131)
Traceback (most recent call last):
  File "/opt/airflow/dags/finance_data_generator.py", line 21, in generate_and_store_data
    df = generate_financial_transactions()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/data_generator.py", line 70, in generate_financial_transactions
    'transaction_id': generate_transaction_ids(size),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/data_generator.py", line 27, in generate_transaction_ids
    ids = range(start_id + 1, start_id + size + 1)
                ~~~~~~~~~^~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/finance_data_generator.py", line 25, in generate_and_store_data
    raise AirflowFailException(f"Data generation or storage failed: {e}")
airflow.exceptions.AirflowFailException: Data generation or storage failed: unsupported operand type(s) for +: 'NoneType' and 'int'
[2024-12-05T06:11:03.213+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T06:11:03.234+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T06:11:03.239+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
