[2024-12-05T05:53:31.185+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T05:53:31.213+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-05T05:52:00+00:00 [queued]>
[2024-12-05T05:53:31.227+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-05T05:52:00+00:00 [queued]>
[2024-12-05T05:53:31.228+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-05T05:53:31.249+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_and_store_data> on 2024-12-05 05:52:00+00:00
[2024-12-05T05:53:31.263+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'finance_data_generator', 'generate_and_store_data', 'scheduled__2024-12-05T05:52:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/finance_data_generator.py', '--cfg-path', '/tmp/tmpwan_qb8e']
[2024-12-05T05:53:31.266+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask generate_and_store_data
[2024-12-05T05:53:31.266+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T05:53:31.267+0000] {standard_task_runner.py:72} INFO - Started process 82 to run task
[2024-12-05T05:53:31.343+0000] {task_command.py:467} INFO - Running <TaskInstance: finance_data_generator.generate_and_store_data scheduled__2024-12-05T05:52:00+00:00 [running]> on host d06e2269e0be
[2024-12-05T05:53:31.461+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='finance_data_generator' AIRFLOW_CTX_TASK_ID='generate_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T05:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-05T05:52:00+00:00'
[2024-12-05T05:53:31.463+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-05T05:53:31.463+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-05T05:53:31.464+0000] {logging_mixin.py:190} INFO - Current task name:generate_and_store_data state:running start_date:2024-12-05 05:53:31.213882+00:00
[2024-12-05T05:53:31.465+0000] {logging_mixin.py:190} INFO - Dag name:finance_data_generator and current dag run status:running
[2024-12-05T05:53:31.465+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T05:53:31.513+0000] {logging_mixin.py:190} INFO - Error storing transactions: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "866c4b25-32d8-4646-a0aa-f3ed71a62737"
LINE 1: ...ory, merchant, payment_method, timestamp) VALUES ('866c4b25-...
                                                             ^

[SQL: INSERT INTO transactions (transaction_id, amount, category, merchant, payment_method, timestamp) VALUES (%(transaction_id)s, %(amount)s, %(category)s, %(merchant)s, %(payment_method)s, %(timestamp)s)]
[parameters: ({'transaction_id': '866c4b25-32d8-4646-a0aa-f3ed71a62737', 'amount': 2190.416847988605, 'category': 'Investment', 'merchant': 'Workshop D', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 2, 48, 31, 468169)}, {'transaction_id': 'c486bdf9-96ad-407f-9b1b-a5c17c49eb6b', 'amount': 4184.075185700469, 'category': 'Education', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 5, 5, 4, 31, 468169)}, {'transaction_id': 'c38465cc-f03a-4ab8-a40d-d7e3b55988ee', 'amount': 3503.3556642641875, 'category': 'Transportation', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 20, 3, 31, 468169)}, {'transaction_id': '5b4507c9-17e7-45cc-964d-2ebe5f9029f1', 'amount': 1331.1034191720992, 'category': 'Transportation', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 13, 55, 31, 468169)}, {'transaction_id': '5fa27615-4c37-44d8-bab8-bd8313e12882', 'amount': 2082.694995123675, 'category': 'Health', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 15, 15, 31, 468169)}, {'transaction_id': 'c49c1897-04c2-462e-a385-36116ec5de3f', 'amount': 656.9432552811057, 'category': 'Health', 'merchant': 'Online Store C', 'payment_method': 'Cash', 'timestamp': datetime.datetime(2024, 12, 5, 1, 54, 31, 468169)}, {'transaction_id': 'aeeaa09d-143e-45e7-99dd-6e872c0a72f6', 'amount': 1001.96889104356, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 16, 19, 31, 468169)}, {'transaction_id': '53dd5988-c31b-4ef4-a946-f48b589b2f53', 'amount': 4959.332776181746, 'category': 'Health', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 21, 18, 31, 468169)}  ... displaying 10 of 100 total bound parameter sets ...  {'transaction_id': '023e6291-786c-477f-acc4-8a8e4e0fe8c1', 'amount': 3618.2456781241613, 'category': 'Electronics', 'merchant': 'Workshop D', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 14, 50, 31, 468169)}, {'transaction_id': 'f975d80e-15e5-444b-b105-b99d875b93a8', 'amount': 2233.9415219258453, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 3, 52, 31, 468169)})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
[2024-12-05T05:53:31.514+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "866c4b25-32d8-4646-a0aa-f3ed71a62737"
LINE 1: ...ory, merchant, payment_method, timestamp) VALUES ('866c4b25-...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/dags/finance_data_generator.py", line 23, in generate_and_store_data
    store_transactions_to_db(df, engine)
  File "/opt/airflow/dags/utils/db_operations.py", line 28, in store_transactions_to_db
    df.to_sql('transactions', engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "866c4b25-32d8-4646-a0aa-f3ed71a62737"
LINE 1: ...ory, merchant, payment_method, timestamp) VALUES ('866c4b25-...
                                                             ^

[SQL: INSERT INTO transactions (transaction_id, amount, category, merchant, payment_method, timestamp) VALUES (%(transaction_id)s, %(amount)s, %(category)s, %(merchant)s, %(payment_method)s, %(timestamp)s)]
[parameters: ({'transaction_id': '866c4b25-32d8-4646-a0aa-f3ed71a62737', 'amount': 2190.416847988605, 'category': 'Investment', 'merchant': 'Workshop D', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 2, 48, 31, 468169)}, {'transaction_id': 'c486bdf9-96ad-407f-9b1b-a5c17c49eb6b', 'amount': 4184.075185700469, 'category': 'Education', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 5, 5, 4, 31, 468169)}, {'transaction_id': 'c38465cc-f03a-4ab8-a40d-d7e3b55988ee', 'amount': 3503.3556642641875, 'category': 'Transportation', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 20, 3, 31, 468169)}, {'transaction_id': '5b4507c9-17e7-45cc-964d-2ebe5f9029f1', 'amount': 1331.1034191720992, 'category': 'Transportation', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 13, 55, 31, 468169)}, {'transaction_id': '5fa27615-4c37-44d8-bab8-bd8313e12882', 'amount': 2082.694995123675, 'category': 'Health', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 15, 15, 31, 468169)}, {'transaction_id': 'c49c1897-04c2-462e-a385-36116ec5de3f', 'amount': 656.9432552811057, 'category': 'Health', 'merchant': 'Online Store C', 'payment_method': 'Cash', 'timestamp': datetime.datetime(2024, 12, 5, 1, 54, 31, 468169)}, {'transaction_id': 'aeeaa09d-143e-45e7-99dd-6e872c0a72f6', 'amount': 1001.96889104356, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 16, 19, 31, 468169)}, {'transaction_id': '53dd5988-c31b-4ef4-a946-f48b589b2f53', 'amount': 4959.332776181746, 'category': 'Health', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 21, 18, 31, 468169)}  ... displaying 10 of 100 total bound parameter sets ...  {'transaction_id': '023e6291-786c-477f-acc4-8a8e4e0fe8c1', 'amount': 3618.2456781241613, 'category': 'Electronics', 'merchant': 'Workshop D', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 14, 50, 31, 468169)}, {'transaction_id': 'f975d80e-15e5-444b-b105-b99d875b93a8', 'amount': 2233.9415219258453, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 3, 52, 31, 468169)})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/finance_data_generator.py", line 25, in generate_and_store_data
    raise AirflowFailException(f"Data generation or storage failed: {e}")
airflow.exceptions.AirflowFailException: Data generation or storage failed: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "866c4b25-32d8-4646-a0aa-f3ed71a62737"
LINE 1: ...ory, merchant, payment_method, timestamp) VALUES ('866c4b25-...
                                                             ^

[SQL: INSERT INTO transactions (transaction_id, amount, category, merchant, payment_method, timestamp) VALUES (%(transaction_id)s, %(amount)s, %(category)s, %(merchant)s, %(payment_method)s, %(timestamp)s)]
[parameters: ({'transaction_id': '866c4b25-32d8-4646-a0aa-f3ed71a62737', 'amount': 2190.416847988605, 'category': 'Investment', 'merchant': 'Workshop D', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 2, 48, 31, 468169)}, {'transaction_id': 'c486bdf9-96ad-407f-9b1b-a5c17c49eb6b', 'amount': 4184.075185700469, 'category': 'Education', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 5, 5, 4, 31, 468169)}, {'transaction_id': 'c38465cc-f03a-4ab8-a40d-d7e3b55988ee', 'amount': 3503.3556642641875, 'category': 'Transportation', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 20, 3, 31, 468169)}, {'transaction_id': '5b4507c9-17e7-45cc-964d-2ebe5f9029f1', 'amount': 1331.1034191720992, 'category': 'Transportation', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 13, 55, 31, 468169)}, {'transaction_id': '5fa27615-4c37-44d8-bab8-bd8313e12882', 'amount': 2082.694995123675, 'category': 'Health', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 15, 15, 31, 468169)}, {'transaction_id': 'c49c1897-04c2-462e-a385-36116ec5de3f', 'amount': 656.9432552811057, 'category': 'Health', 'merchant': 'Online Store C', 'payment_method': 'Cash', 'timestamp': datetime.datetime(2024, 12, 5, 1, 54, 31, 468169)}, {'transaction_id': 'aeeaa09d-143e-45e7-99dd-6e872c0a72f6', 'amount': 1001.96889104356, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 16, 19, 31, 468169)}, {'transaction_id': '53dd5988-c31b-4ef4-a946-f48b589b2f53', 'amount': 4959.332776181746, 'category': 'Health', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 21, 18, 31, 468169)}  ... displaying 10 of 100 total bound parameter sets ...  {'transaction_id': '023e6291-786c-477f-acc4-8a8e4e0fe8c1', 'amount': 3618.2456781241613, 'category': 'Electronics', 'merchant': 'Workshop D', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 14, 50, 31, 468169)}, {'transaction_id': 'f975d80e-15e5-444b-b105-b99d875b93a8', 'amount': 2233.9415219258453, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 3, 52, 31, 468169)})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
[2024-12-05T05:53:31.546+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-05T05:53:31.548+0000] {logging_mixin.py:190} INFO - Task start:2024-12-05 05:53:31.213882+00:00 end:2024-12-05 05:53:31.545407+00:00 duration:0.331525
[2024-12-05T05:53:31.549+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): generate_and_store_data> dag:<DAG: finance_data_generator> dagrun:<DagRun finance_data_generator @ 2024-12-05 05:52:00+00:00: scheduled__2024-12-05T05:52:00+00:00, state:running, queued_at: 2024-12-05 05:53:26.182653+00:00. externally triggered: False>
[2024-12-05T05:53:31.550+0000] {logging_mixin.py:190} INFO - Failure caused by Data generation or storage failed: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "866c4b25-32d8-4646-a0aa-f3ed71a62737"
LINE 1: ...ory, merchant, payment_method, timestamp) VALUES ('866c4b25-...
                                                             ^

[SQL: INSERT INTO transactions (transaction_id, amount, category, merchant, payment_method, timestamp) VALUES (%(transaction_id)s, %(amount)s, %(category)s, %(merchant)s, %(payment_method)s, %(timestamp)s)]
[parameters: ({'transaction_id': '866c4b25-32d8-4646-a0aa-f3ed71a62737', 'amount': 2190.416847988605, 'category': 'Investment', 'merchant': 'Workshop D', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 2, 48, 31, 468169)}, {'transaction_id': 'c486bdf9-96ad-407f-9b1b-a5c17c49eb6b', 'amount': 4184.075185700469, 'category': 'Education', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 5, 5, 4, 31, 468169)}, {'transaction_id': 'c38465cc-f03a-4ab8-a40d-d7e3b55988ee', 'amount': 3503.3556642641875, 'category': 'Transportation', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 20, 3, 31, 468169)}, {'transaction_id': '5b4507c9-17e7-45cc-964d-2ebe5f9029f1', 'amount': 1331.1034191720992, 'category': 'Transportation', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 13, 55, 31, 468169)}, {'transaction_id': '5fa27615-4c37-44d8-bab8-bd8313e12882', 'amount': 2082.694995123675, 'category': 'Health', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 15, 15, 31, 468169)}, {'transaction_id': 'c49c1897-04c2-462e-a385-36116ec5de3f', 'amount': 656.9432552811057, 'category': 'Health', 'merchant': 'Online Store C', 'payment_method': 'Cash', 'timestamp': datetime.datetime(2024, 12, 5, 1, 54, 31, 468169)}, {'transaction_id': 'aeeaa09d-143e-45e7-99dd-6e872c0a72f6', 'amount': 1001.96889104356, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 16, 19, 31, 468169)}, {'transaction_id': '53dd5988-c31b-4ef4-a946-f48b589b2f53', 'amount': 4959.332776181746, 'category': 'Health', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 21, 18, 31, 468169)}  ... displaying 10 of 100 total bound parameter sets ...  {'transaction_id': '023e6291-786c-477f-acc4-8a8e4e0fe8c1', 'amount': 3618.2456781241613, 'category': 'Electronics', 'merchant': 'Workshop D', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 14, 50, 31, 468169)}, {'transaction_id': 'f975d80e-15e5-444b-b105-b99d875b93a8', 'amount': 2233.9415219258453, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 3, 52, 31, 468169)})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
[2024-12-05T05:53:31.550+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=finance_data_generator, task_id=generate_and_store_data, run_id=scheduled__2024-12-05T05:52:00+00:00, execution_date=20241205T055200, start_date=20241205T055331, end_date=20241205T055331
[2024-12-05T05:53:31.573+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T05:53:31.574+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task generate_and_store_data (Data generation or storage failed: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "866c4b25-32d8-4646-a0aa-f3ed71a62737"
LINE 1: ...ory, merchant, payment_method, timestamp) VALUES ('866c4b25-...
                                                             ^

[SQL: INSERT INTO transactions (transaction_id, amount, category, merchant, payment_method, timestamp) VALUES (%(transaction_id)s, %(amount)s, %(category)s, %(merchant)s, %(payment_method)s, %(timestamp)s)]
[parameters: ({'transaction_id': '866c4b25-32d8-4646-a0aa-f3ed71a62737', 'amount': 2190.416847988605, 'category': 'Investment', 'merchant': 'Workshop D', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 2, 48, 31, 468169)}, {'transaction_id': 'c486bdf9-96ad-407f-9b1b-a5c17c49eb6b', 'amount': 4184.075185700469, 'category': 'Education', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 5, 5, 4, 31, 468169)}, {'transaction_id': 'c38465cc-f03a-4ab8-a40d-d7e3b55988ee', 'amount': 3503.3556642641875, 'category': 'Transportation', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 20, 3, 31, 468169)}, {'transaction_id': '5b4507c9-17e7-45cc-964d-2ebe5f9029f1', 'amount': 1331.1034191720992, 'category': 'Transportation', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 13, 55, 31, 468169)}, {'transaction_id': '5fa27615-4c37-44d8-bab8-bd8313e12882', 'amount': 2082.694995123675, 'category': 'Health', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 15, 15, 31, 468169)}, {'transaction_id': 'c49c1897-04c2-462e-a385-36116ec5de3f', 'amount': 656.9432552811057, 'category': 'Health', 'merchant': 'Online Store C', 'payment_method': 'Cash', 'timestamp': datetime.datetime(2024, 12, 5, 1, 54, 31, 468169)}, {'transaction_id': 'aeeaa09d-143e-45e7-99dd-6e872c0a72f6', 'amount': 1001.96889104356, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 16, 19, 31, 468169)}, {'transaction_id': '53dd5988-c31b-4ef4-a946-f48b589b2f53', 'amount': 4959.332776181746, 'category': 'Health', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 21, 18, 31, 468169)}  ... displaying 10 of 100 total bound parameter sets ...  {'transaction_id': '023e6291-786c-477f-acc4-8a8e4e0fe8c1', 'amount': 3618.2456781241613, 'category': 'Electronics', 'merchant': 'Workshop D', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 14, 50, 31, 468169)}, {'transaction_id': 'f975d80e-15e5-444b-b105-b99d875b93a8', 'amount': 2233.9415219258453, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 3, 52, 31, 468169)})]
(Background on this error at: https://sqlalche.me/e/14/9h9h); 82)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "866c4b25-32d8-4646-a0aa-f3ed71a62737"
LINE 1: ...ory, merchant, payment_method, timestamp) VALUES ('866c4b25-...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/dags/finance_data_generator.py", line 23, in generate_and_store_data
    store_transactions_to_db(df, engine)
  File "/opt/airflow/dags/utils/db_operations.py", line 28, in store_transactions_to_db
    df.to_sql('transactions', engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "866c4b25-32d8-4646-a0aa-f3ed71a62737"
LINE 1: ...ory, merchant, payment_method, timestamp) VALUES ('866c4b25-...
                                                             ^

[SQL: INSERT INTO transactions (transaction_id, amount, category, merchant, payment_method, timestamp) VALUES (%(transaction_id)s, %(amount)s, %(category)s, %(merchant)s, %(payment_method)s, %(timestamp)s)]
[parameters: ({'transaction_id': '866c4b25-32d8-4646-a0aa-f3ed71a62737', 'amount': 2190.416847988605, 'category': 'Investment', 'merchant': 'Workshop D', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 2, 48, 31, 468169)}, {'transaction_id': 'c486bdf9-96ad-407f-9b1b-a5c17c49eb6b', 'amount': 4184.075185700469, 'category': 'Education', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 5, 5, 4, 31, 468169)}, {'transaction_id': 'c38465cc-f03a-4ab8-a40d-d7e3b55988ee', 'amount': 3503.3556642641875, 'category': 'Transportation', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 20, 3, 31, 468169)}, {'transaction_id': '5b4507c9-17e7-45cc-964d-2ebe5f9029f1', 'amount': 1331.1034191720992, 'category': 'Transportation', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 13, 55, 31, 468169)}, {'transaction_id': '5fa27615-4c37-44d8-bab8-bd8313e12882', 'amount': 2082.694995123675, 'category': 'Health', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 15, 15, 31, 468169)}, {'transaction_id': 'c49c1897-04c2-462e-a385-36116ec5de3f', 'amount': 656.9432552811057, 'category': 'Health', 'merchant': 'Online Store C', 'payment_method': 'Cash', 'timestamp': datetime.datetime(2024, 12, 5, 1, 54, 31, 468169)}, {'transaction_id': 'aeeaa09d-143e-45e7-99dd-6e872c0a72f6', 'amount': 1001.96889104356, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 16, 19, 31, 468169)}, {'transaction_id': '53dd5988-c31b-4ef4-a946-f48b589b2f53', 'amount': 4959.332776181746, 'category': 'Health', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 21, 18, 31, 468169)}  ... displaying 10 of 100 total bound parameter sets ...  {'transaction_id': '023e6291-786c-477f-acc4-8a8e4e0fe8c1', 'amount': 3618.2456781241613, 'category': 'Electronics', 'merchant': 'Workshop D', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 14, 50, 31, 468169)}, {'transaction_id': 'f975d80e-15e5-444b-b105-b99d875b93a8', 'amount': 2233.9415219258453, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 3, 52, 31, 468169)})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/finance_data_generator.py", line 25, in generate_and_store_data
    raise AirflowFailException(f"Data generation or storage failed: {e}")
airflow.exceptions.AirflowFailException: Data generation or storage failed: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "866c4b25-32d8-4646-a0aa-f3ed71a62737"
LINE 1: ...ory, merchant, payment_method, timestamp) VALUES ('866c4b25-...
                                                             ^

[SQL: INSERT INTO transactions (transaction_id, amount, category, merchant, payment_method, timestamp) VALUES (%(transaction_id)s, %(amount)s, %(category)s, %(merchant)s, %(payment_method)s, %(timestamp)s)]
[parameters: ({'transaction_id': '866c4b25-32d8-4646-a0aa-f3ed71a62737', 'amount': 2190.416847988605, 'category': 'Investment', 'merchant': 'Workshop D', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 2, 48, 31, 468169)}, {'transaction_id': 'c486bdf9-96ad-407f-9b1b-a5c17c49eb6b', 'amount': 4184.075185700469, 'category': 'Education', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 5, 5, 4, 31, 468169)}, {'transaction_id': 'c38465cc-f03a-4ab8-a40d-d7e3b55988ee', 'amount': 3503.3556642641875, 'category': 'Transportation', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 20, 3, 31, 468169)}, {'transaction_id': '5b4507c9-17e7-45cc-964d-2ebe5f9029f1', 'amount': 1331.1034191720992, 'category': 'Transportation', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 13, 55, 31, 468169)}, {'transaction_id': '5fa27615-4c37-44d8-bab8-bd8313e12882', 'amount': 2082.694995123675, 'category': 'Health', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 15, 15, 31, 468169)}, {'transaction_id': 'c49c1897-04c2-462e-a385-36116ec5de3f', 'amount': 656.9432552811057, 'category': 'Health', 'merchant': 'Online Store C', 'payment_method': 'Cash', 'timestamp': datetime.datetime(2024, 12, 5, 1, 54, 31, 468169)}, {'transaction_id': 'aeeaa09d-143e-45e7-99dd-6e872c0a72f6', 'amount': 1001.96889104356, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 16, 19, 31, 468169)}, {'transaction_id': '53dd5988-c31b-4ef4-a946-f48b589b2f53', 'amount': 4959.332776181746, 'category': 'Health', 'merchant': 'Minimarket B', 'payment_method': 'Bank Transfer', 'timestamp': datetime.datetime(2024, 12, 4, 21, 18, 31, 468169)}  ... displaying 10 of 100 total bound parameter sets ...  {'transaction_id': '023e6291-786c-477f-acc4-8a8e4e0fe8c1', 'amount': 3618.2456781241613, 'category': 'Electronics', 'merchant': 'Workshop D', 'payment_method': 'Debit Card', 'timestamp': datetime.datetime(2024, 12, 4, 14, 50, 31, 468169)}, {'transaction_id': 'f975d80e-15e5-444b-b105-b99d875b93a8', 'amount': 2233.9415219258453, 'category': 'Entertainment', 'merchant': 'Cinema E', 'payment_method': 'E-Wallet', 'timestamp': datetime.datetime(2024, 12, 5, 3, 52, 31, 468169)})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
[2024-12-05T05:53:31.607+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T05:53:31.637+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T05:53:31.639+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
